### PR TITLE
archiver recovering from panics

### LINKED ISSUE #227: Catch panics from jobs
When a job is processing a repository if a panic is raised, all the jobs that consumer is processing are sent to the buried queue and the consumer finish.

Catching panic we can detect exactly what is failing and with what repositories so we can improve borges better. Also, consumer will still running and processing no problematics repositories.

### PR DESCRIPTION
**Pull request by mcarmonaa**
Catching panics in the archiver allow us to get better information about what is failing to improve borges, and also lets the consumer continue processing repositories.

Closes #227

### CODE REVIEW

File: archiver.go [hunk 1]
```diff
@@ -113,6 +113,19 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
...
+	defer func() {
+		if rcv := recover(); rcv != nil {
+			log.Error("panic while processing repository", "error", rcv)
+
+			r.FetchErrorAt = &now
+			if sErr := a.Store.UpdateFailed(r, model.Pending); sErr != nil {
+				log15.Error("error setting repo as failed", "id", r.ID, "err", err)
+			}
+
+			err = fmt.Errorf(rcv.(string))
```
Comment (erizocosmico) [inline archiver.go]: i would do a type switch here, whatever may come from a recover. Either that or `fmt.Errorf("%v", rcv)`

File: archiver.go [hunk 2]
```diff
@@ -113,6 +113,19 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
 		"last-fetch", r.FetchedAt,
 		"references", len(r.References))
 
+	defer func() {
+		if rcv := recover(); rcv != nil {
+			log.Error("panic while processing repository", "error", rcv)
```
Comment (jfontan) [inline archiver.go]: It would be nice to also have the stacktrace.

Comment (mcarmonaa) [reply archiver.go]: I don't know if it's possible, there are the functions `debug.PrintStack()` and `runtime.Stack()`, but they give you the stacktrace from they are called, so we woudn't have the stacktrace from the instruction which raised the problem.

@src-d/data-retrieval does some of you know how get the stacktrace we want in this case?

**Comment by mcarmonaa** [comment]
The stacktraces thing is addressed in #235. @src-d/data-retrieval Can I mege this PR and move the stacktrace discussion there?

File: archiver.go (hunk 2 above)
Comment (erizocosmico) [reply archiver.go]: https://play.golang.org/p/wVj32VTnYpH `debug.Stack`
