### PR TITLE
Fix: set status properly for failed repos

### LINKED ISSUE #231: Status not set properly when consumer unexpectedly fails
If the consumer fails with a panic (or the system kill it unexpectedly, etc), all those repositories it was processing stay in the `borges` queue with status `fetching`.

When other consumer find any of these repos in the `borges` queue, it take that repo, print a warning and then fails the processing and sent the repo to the `buriedQueue`:
```
t=2018-02-09T12:34:27+0100 lvl=dbug msg="repository model obtained" module=borges worker=14 job=01617a25-9623-6b63-ddca-b635746fe567 status=fetching last-fetch=nil references=0 caller=archiver.go:132
t=2018-02-09T12:34:27+0100 lvl=warn msg="cannot process repository" module=borges worker=14 job=01617a25-9623-6b63-ddca-b635746fe567 id=01617a25-9623-6b63-ddca-b635746fe567 last-fetch=nil reason="repository 01617a25-9623-6b63-ddca-b635746fe567 was already in a fetching status" caller=archiver.go:151
t=2018-02-09T12:34:27+0100 lvl=eror msg="job finished with error" module=borges worker=14 job=01617a25-9623-6b63-ddca-b635746fe567 error="repository 01617a25-9623-6b63-ddca-b635746fe567 was already in a fetching status" caller=archiver.go:99
t=2018-02-09T12:34:27+0100 lvl=eror msg="error on job" module=borges worker=14 error="repository 01617a25-9623-6b63-ddca-b635746fe567 was already in a fetching status" caller=worker.go:50
```
The problem is that when the consumer sends one of this repositories to the `buriedQueue`, it doesn't change that repo's status in the database and the status is kept as 'fetching' instead of `pending`.

So when if you requeue this repositories, all the process is repeated again and again and those  repos are never processed.

### PR DESCRIPTION
**Pull request by mcarmonaa**
Fixes #231

### CODE REVIEW

**Comment by ajnavarro** [comment]
Also some tests would be awesome

File: archiver.go [hunk 1]
```diff
@@ -121,6 +121,11 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
 		)
 
 		metrics.RepoSkipped()
+		r.FetchErrorAt = &now
```
Comment (erizocosmico) [inline archiver.go]: if the repo is marked as failed, then it does not make sense to have `metrics.RepoSkipped` called because it was not skipped, it was failed

File: archiver.go [hunk 2]
```diff
@@ -200,12 +199,21 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
 	return nil
 }
 
-func (a *Archiver) canProcessRepository(repo *model.Repository) error {
+func (a *Archiver) canProcessRepository(repo *model.Repository, now *time.Time) (err error) {
+	defer func() {
+		if err != nil {
```
Comment (erizocosmico) [inline archiver.go]: why is this logic in a defer instead of just after the `if` checking the status?

**Comment by mcarmonaa** [comment]
I already added a test and changed the other required things.

File: archiver.go (hunk 2 above)
Comment (mcarmonaa) [reply archiver.go]: Because if in the future we have more wrong statuses we can handle all of them just with a `switch` and setting err for each case. Should I change it for the current only one case?

**Comment by mcarmonaa** [comment]
ping @erizocosmico
