### PR TITLE
Fixed hdfs reconnection

### LINKED ISSUE #217: Reconnect to HDFS if it fails
Add a way to reconnect to HDFS if it fails. Right now if HDFS disconnect temporally, borges is not able to work properly and reconnect again.

### PR DESCRIPTION
**Pull request by mcarmonaa**
Now when a namenode error is detected either at the beginning of a transaction or when it's going to be committed, there are some retries to reconnect to HDFS so the consumer can continue processing repos.

Closes #217

### CODE REVIEW

File: archiver.go [hunk 1]
```diff
@@ -18,6 +17,9 @@ import (
 	"gopkg.in/src-d/go-git.v4/plumbing"
 	"gopkg.in/src-d/go-git.v4/plumbing/transport"
 	"gopkg.in/src-d/go-kallax.v1"
+
+	"github.com/inconshreveable/log15"
+	"github.com/jpillora/backoff"
```
Comment (erizocosmico) [inline archiver.go]: these should go before the gopkg.in imports

File: archiver.go [hunk 2]
```diff
@@ -39,6 +41,8 @@ var (
 type Archiver struct {
 	log log15.Logger
 
+	backoff *backoff.Backoff
```
Comment (erizocosmico) [inline archiver.go]: A single instance of `Archiver` can only process a single repo at a time, right?

File: archiver.go (hunk 1 above)
Comment (mcarmonaa) [reply archiver.go]: Aren't we separating our libraries from third libraries in the imports declaration? :thinking:

File: archiver.go (hunk 2 above)
Comment (mcarmonaa) [reply archiver.go]: Right, for each job a new archiver is intantiated

File: archiver.go (hunk 1 above)
Comment (erizocosmico) [reply archiver.go]: yes, but it's alphabetical and `github.com` < `gopkg.in`

File: archiver.go (hunk 2 above)
Comment (erizocosmico) [reply archiver.go]: cool, then it's ok

File: archiver.go (hunk 1 above)
Comment (mcarmonaa) [reply archiver.go]: Ok, I'm changing it :+1: , anyway I thought that this convention was:
```go
import (
        "a-stdlib"
        "b-stdlib"
        "c-stdlib"

        "a-ourlib"
        "b-ourlib"
        "c-ourlib"

        "a-thirdpartylib"
        "b-thirdpartylib"
        "b-thirdpartylib"
)
```
