### PR TITLE
set repositories as fetching until they're fully fetched

### LINKED ISSUE #112: If borges crashes, jobs are not sent to the dead letter queue
See https://github.com/src-d/borges/issues/26
When borges finds an error and rejects a job (ack + err) it sends the job to the dead letter queue. However, this is not being done when borges crashes.

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #112 

This PR introduces a mechanism to ensure fatal errors do not lead to repositories being incorrectly reprocessed. To do this, when a consumer worker receives a job, it checks if the repository has the `fetching` status. If it does, it means there was a fatal error when it started processing and returns an error, which leads to the job being rejected and it's thus sent to the dead letter queue.
Immediately after that, the worker sets the status of the repository to `fetching` if it's any other status and continues normally until the end, when the status is changed to `not_found`, `fetched` or `pending` depending on the circumstances at the end of the process.

So, after the job is process (or not, if it crashes) this are the possible statuses of a repository:

* Process crashed: `fetching`
* Repo not found:  `not_found`
* All ok: `fetched` 
* Any other error: `pending` and `FetchErrorAt` is updated

### CODE REVIEW

File: archiver.go [hunk 1]
```diff
@@ -89,6 +90,19 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
 		"last-fetch", r.FetchedAt,
 		"references", len(r.References))
 
+	if r.Status == model.Fetching {
```
Comment (ajnavarro) [inline archiver.go]: can we move this block to a separate method?

File: archiver.go [hunk 2]
```diff
@@ -107,6 +121,7 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
 			finalErr = ErrClone.Wrap(err, endpoint)
 		}
 
+		r.Status = model.Pending
```
Comment (ajnavarro) [inline archiver.go]: we can move this inside the method dbUpdateFailedRepository

File: archiver.go [hunk 3]
```diff
@@ -138,6 +153,13 @@ func (a *Archiver) do(log log15.Logger, j *Job) (err error) {
 	log.Debug("changes obtained", "roots", len(changes))
 	if err := a.pushChangesToRootedRepositories(log, j, r, gr, changes, now); err != nil {
 		log.Error("repository processed with errors", "error", err)
+
+		r.Status = model.Pending
```
Comment (ajnavarro) [inline archiver.go]: we can move this inside the method dbUpdateFailedRepository

File: archiver.go (hunk 1 above)
Comment (erizocosmico) [inline archiver.go]: The whole if branch or the `r.Status == model.Fetching`?

File: archiver.go (hunk 2 above)
Comment (erizocosmico) [inline archiver.go]: If we do, we'd need another method to update when is not found. Right now, `dbUpdateFailedRepository` also saves the repository when it's status is `NotFound`

File: archiver.go (hunk 3 above)
Comment (erizocosmico) [inline archiver.go]: See reply to previous comment

File: archiver.go (hunk 2 above)
Comment (erizocosmico) [inline archiver.go]: Or we could simply add a `model.FetchStatus` parameter to `dbUpdateFailedRepository` and make it explicit that it needs to receive a status

File: archiver.go (hunk 1 above)
Comment (ajnavarro) [inline archiver.go]: the entire if.

Comment (erizocosmico) [inline archiver.go]: If we move this to a method it will become:

```go
if err := a.foo(); err != nil {
  return err
}
```
or 

```go
if a.foo() {
  return ErrAlreadyFetching.New(blabla)
}
```

Which is exactly as long as it is now (excluding the log, that I would not move to the method). Not sure what benefit would we obtain from moving this to a method

**Comment by erizocosmico** [comment]
Done @ajnavarro
